
CAR_DB:list[dict]=None

CAR_DB=[
    {
        "id":1,
        "name":"849 Testarossa",
        "brand":"Ferrari",
        "price":"₹10.37 Cr",
        "image_url":"https://carconfigurator.ferrari.com/f173m/22470b9f5dd1fd8e58e5c11a5d5f1d24313d2a87b7c9ce72f69833c2bec48406-Blackroom-Day-beautyshot_ext_frontleft-2d.jpg",
    },
    {
        "id":2,
        "name":"SF90 XX Stradale",
        "brand":"Ferrari",
        "price":"₹6.90 Cr",
        "image_url":"https://cdn.ferrari.com/cms/network/media/img/resize/64994752096d6200233aabf2-ferrari-sf90-xx-stradale-intro-desk-mob-new?width=768&height=1024",
    },
    {
        "id":3,
        "name":"S 350d",
        "brand":"Mercedes Benz",
        "price":"₹1.81 Cr",
        "image_url":"https://media.oneweb.mercedes-benz.com/images/dynamic/europe/IN/223120/805_055/iris.png?q=COSY-EU-100-1713d0VXqrW7qtyO67PobzIr3eWsrrCsdRRzwQZgk4ZbMw3SGtGyjtsd2vtcUfp8cXGEubYJ0l36xOB2NS5bApj7bI5uVKDQC31MrkzNwTbm7jZ6vhKVFKE%25vq9UTyLRDGmYaxW0ErH1dItn8wvOyoiZLbgM4Fa4MTg9Hvk6PD8cqSeWiyMtsd4YtcUfC%25kXGEzbjJ0l7IJOB2KMjbApvdyI5uLfJQC3akOkzNHmdm7jgevhKVPs9%25vqAtdyLR5LDYaxCbxrH1zjRn8w7hnoiZK%251M4FvTJTg9L6k6PDaGbSeWH0Utsd8BDcUfDO6XGE5GXJ0lCrnOIJtR1q9ooiZeIQM6o2xgTSMsQ26PDLLqSeWvK3tsdPvQcUfercXGE19jJ0lB0tOB2ABnbAp5iwI5uCeZQCPFi2J%25xVZkF7oZ7IG3MkNulKlO1OsxACeqUx4Wgj%25Xi5o&BKGND=9&IMGT=P27&cp=U7lLKRUtPa6KAFr8s_ubHw&uni=m&POV=BE040,PZM",
    },
    {
        "id": 4,
        "name": "GT3 RS",
        "brand": "Porsche",
        "price": "₹2.75 Cr",
        "image_url": "https://mediaassets.pca.org/pages/pca/images/content/04-PCA-Porsche-911-GT3-RS.jpg",
    },
    {
        "id": 5,
        "name": "Huracán EVO",
        "brand": "Lamborghini",
        "price": "₹3.73 Cr",
        "image_url": "https://hips.hearstapps.com/hmg-prod/images/2020-lamborghini-huracan-evo-rwd-110-1599740187.jpg",
    },
    {
        "id": 6,
        "name": "Chiron Super Sport",
        "brand": "Bugatti",
        "price": "₹19.21 Cr",
        "image_url": "x",
    },
    {
        "id": 7,
        "name": "Aventador SVJ",
        "brand": "Lamborghini",
        "price": "₹6.25 Cr",
        "image_url": "x",
    },
    {
        "id": 8,
        "name": "LaFerrari",
        "brand": "Ferrari",
        "price": "₹12.50 Cr",
        "image_url": "x",
    },
    {
        "id": 9,
        "name": "918 Spyder",
        "brand": "Porsche",
        "price": "₹10.84 Cr",
        "image_url": "x",
    },
    {
        "id": 10,
        "name": "Senna",
        "brand": "McLaren",
        "price": "₹8.00 Cr",
        "image_url": "x",
    },
    {
        "id": 11,
        "name": "Valkyrie",
        "brand": "Aston Martin",
        "price": "₹21.00 Cr",
        "image_url": "x",
    },
    {
        "id": 12,
        "name": "Regera",
        "brand": "Koenigsegg",
        "price": "₹17.00 Cr",
        "image_url": "x",
    },
    {
        "id": 13,
        "name": "Jesko",
        "brand": "Koenigsegg",
        "price": "₹22.00 Cr",
        "image_url": "x",
    },
    {
        "id": 14,
        "name": "Huayra Roadster",
        "brand": "Pagani",
        "price": "₹18.00 Cr",
        "image_url": "x",
    },
    {
        "id": 15,
        "name": "Phantom VIII",
        "brand": "Rolls Royce",
        "price": "₹9.50 Cr",
        "image_url": "x",
    },
    {
        "id": 16,
        "name": "Continental GT",
        "brand": "Bentley",
        "price": "₹3.57 Cr",
        "image_url": "x",
    },
    {
        "id": 17,
        "name": "Ghost",
        "brand": "Rolls Royce",
        "price": "₹6.95 Cr",
        "image_url": "x",
    },
    {
        "id": 18,
        "name": "Urus",
        "brand": "Lamborghini",
        "price": "₹3.15 Cr",
        "image_url": "x",
    },
    {
        "id": 19,
        "name": "DBS Superleggera",
        "brand": "Aston Martin",
        "price": "₹5.36 Cr",
        "image_url": "x",
    },
    {
        "id": 20,
        "name": "Cullinan",
        "brand": "Rolls Royce",
        "price": "₹7.18 Cr",
        "image_url": "x",
    },
    {
        "id": 21,
        "name": "Flying Spur",
        "brand": "Bentley",
        "price": "₹3.41 Cr",
        "image_url": "x",
    },
    {
        "id": 22,
        "name": "GT-R Nismo",
        "brand": "Nissan",
        "price": "₹2.12 Cr",
        "image_url": "x",
    },
    {
        "id": 23,
        "name": "AMG GT Black Series",
        "brand": "Mercedes Benz",
        "price": "₹5.50 Cr",
        "image_url": "x",
    },
    {
        "id": 24,
        "name": "M8 Competition",
        "brand": "BMW",
        "price": "₹2.18 Cr",
        "image_url": "x",
    },
    {
        "id": 25,
        "name": "R8 V10 Plus",
        "brand": "Audi",
        "price": "₹2.72 Cr",
        "image_url": "x",
    },
    {
        "id": 26,
        "name": "SLS AMG",
        "brand": "Mercedes Benz",
        "price": "₹2.54 Cr",
        "image_url": "x",
    },
    {
        "id": 27,
        "name": "MC20",
        "brand": "Maserati",
        "price": "₹3.65 Cr",
        "image_url": "x",
    },
    {
        "id": 28,
        "name": "F8 Tributo",
        "brand": "Ferrari",
        "price": "₹4.02 Cr",
        "image_url": "x",
    },
    {
        "id": 29,
        "name": "Roma",
        "brand": "Ferrari",
        "price": "₹3.76 Cr",
        "image_url": "x",
    },
    {
        "id": 30,
        "name": "Chiron Pur Sport",
        "brand": "Bugatti",
        "price": "₹21.00 Cr",
        "image_url": "x",
    }
]